version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: husky
    versions:
    - 5.1.2
  - dependency-name: "@types/puppeteer"
    versions:
    - 5.4.3
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.31
  - dependency-name: puppeteer
    versions:
    - 8.0.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
  - dependency-name: bl
    versions:
    - 4.1.0
